In [27]:
import numpy as np

In [15]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [13]:
array_2d = np.array([range(5), range(5)])
array_2d 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [29]:
print(array.shape)
print(array_2d.shape)

(5,)
(2, 5)


In [27]:
print(array.size)
print(array_2d.size)

5
10


In [31]:
print(array.ndim)
print(array_2d.ndim)

1
2


In [33]:
print(array.dtype)
print(array_2d.dtype)

int32
int32


In [35]:
np.array(['I','love','Python'])

array(['I', 'love', 'Python'], dtype='<U6')

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones(2, dtype='int')

array([1, 1])

In [44]:
np.zeros(100, 'int').reshape(10, 10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [52]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [62]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [66]:
rng = np.random.default_rng(616)

rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [68]:
rng.integers(0, 10, 100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [70]:
rng.normal(50, 5, 10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

In [2]:
integer_array = np.arange(12)

In [3]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
integer_array[2]

np.int64(2)

In [5]:
integer_array[-1]

np.int64(11)

In [6]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [7]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [8]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [10]:
new_array = integer_array.reshape(3, 4)

new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
new_array[:, 3]

array([ 3,  7, 11])

In [15]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [16]:
new_array[2, 1]

np.int64(9)

In [17]:
ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [18]:
ages[1:4]

array([10, 15, 19])

In [21]:
ages[5:14]

array([25, 30, 35, 40, 45, 50, 55, 60, 65])

In [26]:
ages[-3:]

array([70, 75, 80])

In [11]:
rng = np.random.default_rng(616)

inventory = rng.integers(1, 100, 10)

inventory

array([39, 40, 93, 86, 49, 46, 49, 31, 12, 57], dtype=int64)

In [13]:
inventory - 24

array([ 15,  16,  69,  62,  25,  22,  25,   7, -12,  33], dtype=int64)

In [15]:
inventory / 2

array([19.5, 20. , 46.5, 43. , 24.5, 23. , 24.5, 15.5,  6. , 28.5])

In [25]:
price = (rng.random(10) * 10).round(2)

price

array([5.24, 8.02, 0.75, 1.51, 8.97, 6.63, 7.26, 7.66, 0.3 , 7.78])

In [29]:
(price * inventory).sum()

2509.54

In [33]:
inventory_list = list(inventory)

inventory_list

[39, 40, 93, 86, 49, 46, 49, 31, 12, 57]

In [28]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [30]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
even_odd = np.array(['even','odd'] * 10)

even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [34]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [35]:
even_ood[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [36]:
my_array[even_ood != 'odd'] = 0

my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [37]:
mask = (even_odd != 'odd') | (even_odd != 'even')

even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [38]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
np.where(my_array %2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [42]:
np.where(my_array %2 == 0, 'even', np.where(my_array == 9, my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

In [49]:
import numpy as np

# Provided array of ages
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

adult_ages = ages > 17

ages[adult_ages]

array([25, 64, 35, 80, 45, 22, 55])

In [2]:
import numpy as np

rng = np.random.default_rng(616)

prices = (rng.random(10) * 10).round(2)

prices

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [11]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [21]:
prices.mean()

5.6

In [25]:
inventory.mean()

35.3

In [29]:
inventory.sum()
inventory.max()
inventory.min()

6

In [41]:
(prices * inventory)
(prices * inventory).sum().round(2)

1848.29

In [45]:
prices_2d = prices.reshape(5, 2)
prices_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [47]:
prices_2d.sum(axis=0)

array([30.45, 25.55])

In [49]:
prices_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [12]:
import numpy as np

rng = np.random.default_rng(616)

prices = (rng.random(10) * 10).round(2)

inventory = rng.integers(0, 100, 10)

product_value = prices * inventory

product_value 

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [16]:
reshaped_product_value = product_value.reshape(2, 5)

reshaped_product_value

array([[317.6 , 285.78, 276.  ,  18.36, 177.94],
       [ 31.15, 141.12, 146.4 , 212.28, 241.66]])

In [18]:
np.median(reshaped_product_value)

195.11

In [26]:
np.percentile(reshaped_product_value, 90)

288.962

In [28]:
np.sqrt(reshaped_product_value)

array([[17.82133553, 16.90502884, 16.61324773,  4.28485706, 13.33941528],
       [ 5.5812185 , 11.87939392, 12.09958677, 14.56983185, 15.54541733]])

In [30]:
np.unique(reshaped_product_value)

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [32]:
product_value 

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [36]:
np.sort(product_value)[:5]

array([ 18.36,  31.15, 141.12, 146.4 , 177.94])

In [38]:
product_value.sort()

In [40]:
product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [42]:
product_value[::-1]

array([317.6 , 285.78, 276.  , 241.66, 212.28, 177.94, 146.4 , 141.12,
        31.15,  18.36])